# Generated by Django 3.0.8 on 2020-11-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='Unsorted', max_length=255),
            preserve_default=False,
        ),
    ]
