# Generated by Django 3.0.8 on 2020-11-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=1000)),
                ('genre', models.CharField(max_length=255)),
                ('page_count', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
